# Generated by Django 5.2.11 on 2026-02-13 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Titre de l'offre d'emploi", max_length=255)),
                ('description', models.TextField(help_text='Description détaillée du poste et des responsabilités')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Salaire proposé (optionnel)', max_digits=10, null=True)),
                ('skills', models.JSONField(blank=True, default=list, help_text='Liste de compétences requises')),
                ('publication_date', models.DateTimeField(auto_now_add=True, help_text='Date et heure de publication automatiques')),
                ('active', models.BooleanField(default=True, help_text="L'offre est-elle active?")),
                ('company', models.ForeignKey(help_text="Entreprise qui publie l'offre", on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-publication_date'],
            },
        ),
    ]
